// Advertisement Schema Types
export interface Advertisement {
  id: string // autogenerated
  title: string
  subtitle: string
  description: string
  startDate?: Date
  expirationDate?: Date

  // Foreign Key Relations
  coverImage: File
  thumbnailImage: File
  category: AdvertiseCategory
  subCategory: AdvertiseIndustry
  dealType: AdvertiseDealType

  // List Relations
  locations: AdvertiseLocation[]
  relatedAdvertises: AdvertiseRelatedAdvertise[]
  additionalImages: AdvertiseAdditionalImage[]
  tags: AdvertiseTag[]
  owners: AdvertiseOwner[]
}

// Related Entity Types
export interface File {
  id: string
  filename: string
  url: string
  mimeType: string
  size: number
}

export interface AdvertiseCategory {
  id: string
  name: string
  description?: string
}

export interface AdvertiseIndustry {
  id: string
  name: string
  description?: string
  categoryId: string
}

export interface AdvertiseDealType {
  id: string
  name: string
  description?: string
}

export interface AdvertiseLocation {
  id: string
  advertisementId: string
  name: string
  address?: string
  city: string
  state?: string
  country: string
  latitude?: number
  longitude?: number
}

export interface AdvertiseRelatedAdvertise {
  id: string
  advertisementId: string
  relatedAdvertisementId: string
}

export interface AdvertiseAdditionalImage {
  id: string
  advertisementId: string
  file: File
  order: number
}

export interface AdvertiseTag {
  id: string
  advertisementId: string
  name: string
  color?: string
}

export interface AdvertiseOwner {
  id: string
  advertisementId: string
  name: string
  email?: string
  phone?: string
  type: 'primary' | 'secondary'
}

// Form Data Types
export interface AdvertisementFormData {
  title: string
  subtitle: string
  description: string
  startDate?: string
  expirationDate?: string
  categoryId: string
  subCategoryId: string
  dealTypeId: string
  coverImageFile?: File
  thumbnailImageFile?: File
  locations: Omit<AdvertiseLocation, 'id' | 'advertisementId'>[]
  additionalImageFiles?: File[]
  tags: Omit<AdvertiseTag, 'id' | 'advertisementId'>[]
  owners: Omit<AdvertiseOwner, 'id' | 'advertisementId'>[]
}

// API Response Types
export interface AdvertisementListResponse {
  success: boolean
  message: string
  data: {
    items: AdvertisementApiItem[]
    totalItems: number
    page: number
    pageSize: number
    totalPages: number
  }
}

export interface AdvertisementApiItem {
  id: string
  title: string
  subtitle: string
  description: string | null
  startDate: string | null
  expirationDate: string | null
  coverImageId: string | null
  thumbnailImageId: string | null
  categoryId: string | null
  subCategoryId: string | null
  createdById: string
  createdAt: string
  updatedAt: string
}

// Display Types for Table
export interface AdvertisementDisplay {
  id: string
  title: string
  subtitle: string
  description: string
  startDate?: string
  expirationDate?: string
  categoryName: string
  subCategoryName: string
  dealTypeName: string
  coverImageUrl?: string
  thumbnailImageUrl?: string
  tagCount: number
  locationCount: number
  ownerCount: number
  status: 'draft' | 'published' | 'expired' | 'paused'
  createdAt: string
  updatedAt: string
}
